### ISSUE TITLE
Do not show share button on desktop

### ISSUE THREAD

**Issue by tomayac** [tomayac/fugu-greetings#15]

**Comment by christianliebel** [comment]
I’m not sure if/how we should mitigate this, as exposing the API although it‘s not usable is a browser bug in the first place IMHO. We could sure do user agent testing, but it doesn’t feel right.

**Comment by tomayac** [comment]
Meta bug for this: https://crbug.com/770595. 

We could `try... catch` the error and in the error message point to the bug.

**Comment by tomayac** [comment]
The API is only exposed when the experimental web platform features flag is set. Closing then.
