### ISSUE TITLE
Wallpaper button should be disabled/hidden if we don't have one

### ISSUE THREAD

**Issue by christianliebel** [tomayac/fugu-greetings#3]
When we don't have a wallpaper cached via Periodic Background Sync API, we shouldn't show the button or disable it. I would prefer disabling it so we can at least see if Periodic Sync would be available.

**Comment by tomayac** [comment]
I'm in the middle of restructuring this, but even with the current code there's always a [fallback image](https://github.com/tomayac/fugu-greetings/blob/e3969067af2226bcb68bda4b77ff1923efcc8462/public/js/periodic_background_sync.mjs#L30) in the cache in the case Periodic Background Sync hasn't run (successfully) yet.
